#!/usr/bin/php
<?php
if ($argv[1] == 'config') {
    echo "graph_category nginx
        graph_title Nginx request time
        graph_vlabel %
        graph_scale no
        graph_args --base 1000 -r --lower-limit 0 --upper-limit 100
        t0.label Fast (50ms)
        t0.draw AREA
        t0.type GAUGE
        t0.min 0
        t1.label Medium (100ms)
        t1.draw STACK
        t1.type GAUGE
        t1.min 0
        t2.label Slow (1s)
        t2.draw STACK
        t2.type GAUGE
        t2.min 0
        t3.label Anomaly (1s+)
        t3.draw STACK
        t3.type GAUGE
        t3.min 0
    ";
} else {
    $result = `grep 'rt=' /var/log/nginx/access.log | grep '(?<=rt=).*' -oP`;
    $resultArray = explode("\n", $result);
    $return = array(0, 0, 0, 0);
    if (count($resultArray)) {
        foreach ($resultArray as $one) {
            if ($one < 0.05) {
                $return[0] ++;
            } elseif ($one < 0.1) {
                $return[1] ++;
            } elseif ($one < 1) {
                $return[2] ++;
            } else {
                $return[3] ++;
            }
        }
    }
    $all_request = array_sum($return);
    foreach ($return as $key => $one) {
        $value = round(($one / $all_request * 100), 4);
        echo 't' . $key . '.value ' . $value . "\n";
    }
}
